### ISSUE TITLE
Smooth scrolling

### ISSUE THREAD

**Issue by GiancarloPozzoCoEPP** [george-thomas-hill/thunderkey#1]
Would be possible to have a smooth scrolling feature?

At the moment, scrolling an email with Meta+Left/Right "jumps" from one line to another. This does not happen with the smooth scrolling option provided by Thunderbird (Preference > General > Scrolling > Use smooth scrolling).

Thank you for the very nice addons!! :)

**Comment by george-thomas-hill** [comment]
Thank you very much for the suggestion and the compliment.

At the moment, I don't have time to go in and add a smooth scrolling option.

I will keep that suggestion in mind, however, for any future versions.
